### PR TITLE
Implement Future for SmallBox<F> where F: Future

### PR DESCRIPTION
**Pull request by PonasKovas**
Previously discussed in #38 

Additionally I ran `cargo fmt` in the repository.

I am pretty certain that this is safe and sound, but if you want to discuss this further I will gladly do so.

Closes https://github.com/andylokandy/smallbox/issues/38

### CODE REVIEW

**Comment by andylokandy** [comment]
would you like to add an example demonstrating how SmallBox<Future> can be uesd in async context?

**Comment by PonasKovas** [comment]
You mean demonstrate to you, or add it to the repository somewhere? To the readme?

**Comment by PonasKovas** [comment]
It's really pretty simple, similar to the std `Box` in user-facing code, but doesn't need to be pinned with `Box::pin`

Here's a simple example:

```rust
async fn foo() {
    let fut = async {
        let x = Box::new(123);
        sleep(Duration::from_secs(1)).await;
        println!("{x}");
    };

    let boxed_fut: SmallBox<_, S1> = SmallBox::new(fut);

    let erased = boxed_fut as SmallBox<dyn Future<Output = ()>, S1>;

    erased.await;
}
```

**Review by andylokandy — APPROVED** [review]

**Comment by andylokandy** [comment]
Looks good to me. And would you like to add the async example into the unit tests, to ensure the impl Future works?

**Comment by PonasKovas** [comment]
@andylokandy I could, but then I would need to pull in some `dev-dependencies`, either some framework like `tokio` or `futures` crate. Tell me if that's okay.

Personally I don't think this needs any testing since this feature is pretty much a compile time thing.

**Comment by andylokandy** [comment]
is pollster ok?

**Comment by PonasKovas** [comment]
Yes. I will do it with `pollster` then

**Comment by andylokandy** [comment]
There is a conflict in the commit. I'll merge once it's resolved.

**Comment by PonasKovas** [comment]
Hmm probably pollster doesn't support this MSRV

**Comment by PonasKovas** [comment]
I can switch to `futures` crate, it's MSRV is also 1.56

**Comment by andylokandy** [comment]
Released 0.8.6 https://github.com/andylokandy/smallbox/pull/41

**Pull request merged**
